name: gastro
description: "Unsere Innovation der Zukunft"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.4.6
  firebase_database: ^10.4.0
  firebase_performance: ^0.9.3+8
  google_maps_flutter: ^2.5.3
  shared_preferences: ^2.2.2
  location: ^5.0.0
  geocoding: ^2.1.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true